### PR TITLE
allow passing options into chokidar.

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
I think I messed up indentation a little, sorry. Not sure what rules you were using there. But this makes chokidar usable over NFS for me, as I can enable "usePolling"

### CODE REVIEW

**Comment by TrySound** [comment]
@SevereOverfl0w Hi, thanks for interest. I don't use and support it now. [gulp-watch](https://github.com/floatdrop/gulp-watch) is more flexible.

**Comment by TrySound** [comment]
@SevereOverfl0w Do you need next publish, or you will try gulp-watch?

**Comment by SevereOverfl0w** [comment]
I'll give a quick look at gulp-watch, currently using my git repo as a master in my package.json

**Comment by TrySound** [comment]
@SevereOverfl0w Ok.

**Pull request merged**
